package ru.anontmization.dataanonymizationtool.Methods.options.type;

import ru.anontmization.dataanonymizationtool.Methods.options.MaskItem;
import ru.anontmization.dataanonymizationtool.services.ControllerDataBaseService;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;

public class DateAging implements MaskItem {
    private final String nameTable;
    private final String nameColumn;
    private final int countDays;

    public DateAging(String nameTable, String nameColumn, int countDays) {
        this.nameTable = nameTable;
        this.nameColumn = nameColumn;
        this.countDays = countDays;
    }

    @Override
    public String getTable() {
        return nameTable;
    }

    @Override
    public void start(ControllerDataBaseService controllerDB) throws SQLException {
        controllerDB.getStatement().execute(
                "ALTER TABLE "+nameTable+" ADD COLUMN masking_method_temp_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE;"
        );

        ResultSet resultSet = controllerDB.getStatement().executeQuery(
                "SELECT "+nameColumn+", masking_method_temp_id " +
                        "FROM "+nameTable+";"
        );
        Date cur;
        while(resultSet.next()){
            cur = resultSet.getDate(1);
            if (cur == null) {
                continue;
            }
            resultSet.updateDate(1, Date.valueOf(cur.toLocalDate().plusDays(countDays)));
            resultSet.updateRow();
        }
        controllerDB.getStatement().execute(
                "ALTER TABLE "+nameTable+" DROP COLUMN masking_method_temp_id;"
        );
    }
}
