package ru.anontmization.dataanonymizationtool.Methods.options.type;


import ru.anontmization.dataanonymizationtool.Methods.options.MaskItem;
import ru.anontmization.dataanonymizationtool.services.ControllerDataBaseService;

import java.sql.ResultSet;
import java.sql.SQLException;

public class ValueReplacement implements MaskItem {
    private final String nameTable;
    private final String nameColumn;
    private final Object value;

    public ValueReplacement(String nameTable, String nameColumn, Object value) {
        this.nameTable = nameTable;
        this.nameColumn = nameColumn;
        this.value = value;
    }

    @Override
    public String getTable() {
        return nameTable;
    }

    @Override
    public void start(ControllerDataBaseService controllerDB) throws SQLException {
        controllerDB.getStatement().execute(
                "ALTER TABLE "+nameTable+" ADD COLUMN masking_method_temp_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE;"
        );

        ResultSet resultSet = controllerDB.getStatement().executeQuery(
                "SELECT "+nameColumn+",masking_method_temp_id" +
                        " FROM "+nameTable+";"
        );
        while(resultSet.next()){
            resultSet.updateObject(1, value);
            resultSet.updateRow();
        }
        controllerDB.getStatement().execute(
                "ALTER TABLE "+nameTable+" DROP COLUMN masking_method_temp_id;"
        );
    }

    @Override
    public String toString() {
        return "ValueReplacement{" +
                "nameTable='" + nameTable + '\'' +
                ", nameColumn='" + nameColumn + '\'' +
                ", value=" + value +
                '}';
    }

}
