package ru.anontmization.dataanonymizationtool.Methods.options.type;

import ru.anontmization.dataanonymizationtool.Methods.options.MaskItem;
import ru.anontmization.dataanonymizationtool.services.ControllerDataBaseService;

import java.sql.ResultSet;
import java.sql.SQLException;

public class ValueReplacementByPattern implements MaskItem {
    private final String nameTable;
    private final String nameColumn;
    private final String regex;
    private final String replacement;

    public ValueReplacementByPattern(String nameTable, String nameColumn, String regex, String replacement) {
        this.nameTable = nameTable;
        this.nameColumn = nameColumn;
        this.regex = regex;
        this.replacement = replacement;
    }

    @Override
    public String getTable() {
        return nameTable;
    }

    @Override
    public void start(ControllerDataBaseService controllerDB) throws SQLException {
        controllerDB.getStatement().execute(
                "ALTER TABLE "+nameTable+" ADD COLUMN masking_method_temp_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE;"
        );
        ResultSet resultSet = controllerDB.getStatement().executeQuery(
                "SELECT "+nameColumn+", masking_method_temp_id " +
                        "FROM "+nameTable+";"
        );

        String newValue;
        while(resultSet.next()){
            try {
                newValue = resultSet.getString(1).replaceAll(regex,replacement);
                resultSet.updateString(1, newValue);
                resultSet.updateRow();
            }catch (Exception ignored){}
        }


        controllerDB.getStatement().execute(
                "ALTER TABLE "+nameTable+" DROP COLUMN masking_method_temp_id;"
        );
    }
}
