package ru.anontmization.dataanonymizationtool.Methods.options.type;

import ru.anontmization.dataanonymizationtool.Methods.options.MaskItem;
import ru.anontmization.dataanonymizationtool.services.ControllerDataBaseService;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;

public class ValueReplacementFromFile implements MaskItem {
    private final String nameTable;
    private final String nameColumn;
    private final String nameFile;

    public ValueReplacementFromFile(String nameTable, String nameColumn, String nameFile) {
        this.nameTable = nameTable;
        this.nameColumn = nameColumn;
        this.nameFile = nameFile;
    }

    @Override
    public String getTable() {
        return nameTable;
    }

    @Override
    public void start(ControllerDataBaseService controllerDB) throws SQLException {
        ArrayList<String> list = new ArrayList<>();
        File file = new File(nameFile);


        FileReader fr ;
        BufferedReader reader;
        try {
            fr = new FileReader(file);
            reader = new BufferedReader(fr);
            String line = reader.readLine();
            while (line != null) {
                list.add(line);
                line = reader.readLine();
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }


        controllerDB.getStatement().execute(
                "ALTER TABLE "+nameTable+" ADD COLUMN masking_method_temp_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE;"
        );

        ResultSet resultSet = controllerDB.getStatement().executeQuery(
                "SELECT "+nameColumn+", masking_method_temp_id " +
                        "FROM "+nameTable+";"
        );
        Random random = new Random();
        int cur;
        while(resultSet.next()){
            cur = random.nextInt(list.size());
            resultSet.updateObject(1, list.get(cur));
            resultSet.updateRow();
        }
        controllerDB.getStatement().execute(
                "ALTER TABLE "+nameTable+" DROP COLUMN masking_method_temp_id;"
        );
    }
}
